version: '3.8'
services:
  api-demo-quebec:
    container_name: api-demo-quebec 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  postgres-compose:
    image: postgres
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=postgresql_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network
networks: 
  postgres-compose-network:
    driver: bridge
